set nu
syntax on
colorscheme peachpuff
set background=dark
filetype plugin indent on
set clipboard+=unnamedplus
set noerrorbells
set hidden
set encoding=utf-8
set scrolloff=3
set smartindent
set noswapfile
set nobackup
set wildmenu
set wildmode=list:longest
set number
set path+=**
set nohlsearch
set incsearch
set noshowmatch
set smartcase
set nowrap
set updatetime=40
